export const shop = {
  name: 'BOBA TIDE',
  date: '2026-07-06',
  owner: '店長 Mia',
  slaTarget: '15 分鐘內出餐',
};

export const drinkMenuItems = [
  {
    sku: 'BT-P01',
    product: '黑糖珍珠',
    zone: '吧台區',
    stock: 8,
    reorderPoint: 12,
    reserved: 6,
    owner: 'Ada',
    channel: 'LINE OA',
    unitPrice: 35,
  },
  {
    sku: 'BT-P02',
    product: '波霸',
    zone: '吧台區',
    stock: 0,
    reorderPoint: 6,
    reserved: 4,
    owner: 'Ben',
    channel: 'LINE OA',
    unitPrice: 38,
  },
  {
    sku: 'BT-C01',
    product: '外帶杯 700ml',
    zone: '包材區',
    stock: 40,
    reorderPoint: 30,
    reserved: 10,
    owner: 'Cara',
    channel: '外送平台',
    unitPrice: 3,
  },
  {
    sku: 'BT-C02',
    product: '封膜膜片',
    zone: '包材區',
    stock: 5,
    reorderPoint: 16,
    reserved: 3,
    owner: 'Dino',
    channel: '外送平台',
    unitPrice: 1,
  },
  {
    sku: 'BT-S01',
    product: '鮮奶',
    zone: '冷藏區',
    stock: 26,
    reorderPoint: 18,
    reserved: 8,
    owner: 'Eli',
    channel: 'LINE OA',
    unitPrice: 55,
  },
  {
    sku: 'BT-S02',
    product: '無糖綠茶原液',
    zone: '冷藏區',
    stock: 3,
    reorderPoint: 8,
    reserved: 2,
    owner: 'Fang',
    channel: '外送平台',
    unitPrice: 40,
  },
];

export const drinkOrders = [
  {
    id: 'BT-20260706-018',
    customer: '陳同學',
    channel: '外送平台',
    status: '待製作',
    priority: 'high',
    zone: '吧台區',
    amount: 95,
    eta: '14:30',
  },
  {
    id: 'BT-20260706-021',
    customer: '林小姐',
    channel: 'LINE OA',
    status: '製作中',
    priority: 'medium',
    zone: '吧台區',
    amount: 65,
    eta: '15:10',
  },
  {
    id: 'BT-20260706-025',
    customer: '王先生',
    channel: '外送平台',
    status: '待取餐',
    priority: 'low',
    zone: '包材區',
    amount: 110,
    eta: '16:20',
  },
  {
    id: 'BT-20260706-031',
    customer: '校園咖啡社',
    channel: 'LINE OA',
    status: '缺料等待',
    priority: 'high',
    zone: '冷藏區',
    amount: 320,
    eta: '13:50',
  },
];

export const zones = [
  { id: 'A', label: '吧台區', utilization: 82, status: 'watch' },
  { id: 'B', label: '包材區', utilization: 61, status: 'good' },
  { id: 'C', label: '冷藏區', utilization: 88, status: 'risk' },
  { id: 'D', label: '甜點區', utilization: 54, status: 'good' },
];
