export const warehouse = {
  name: 'NOVA WAREHOUSE',
  date: '2026-07-05',
  owner: 'Ops Control Team',
  slaTarget: '14:30',
};

export const inventory = [
  {
    sku: 'WH-A01',
    product: '冷鏈保溫箱 18L',
    zone: 'A01',
    stock: 8,
    reorderPoint: 12,
    reserved: 6,
    owner: 'Ada',
    channel: 'B2B Portal',
    unitPrice: 1680,
  },
  {
    sku: 'WH-A07',
    product: '冷鏈保溫箱 32L',
    zone: 'A07',
    stock: 0,
    reorderPoint: 6,
    reserved: 4,
    owner: 'Ben',
    channel: 'LINE OA',
    unitPrice: 2380,
  },
  {
    sku: 'WH-B12',
    product: '醫材防潮收納盒',
    zone: 'B12',
    stock: 14,
    reorderPoint: 10,
    reserved: 5,
    owner: 'Cara',
    channel: 'Enterprise',
    unitPrice: 960,
  },
  {
    sku: 'WH-C08',
    product: '批發出貨封箱耗材組',
    zone: 'C08',
    stock: 5,
    reorderPoint: 16,
    reserved: 3,
    owner: 'Dino',
    channel: 'B2B Portal',
    unitPrice: 420,
  },
  {
    sku: 'WH-D04',
    product: '溫控紀錄貼片',
    zone: 'D04',
    stock: 26,
    reorderPoint: 18,
    reserved: 8,
    owner: 'Eli',
    channel: 'LINE OA',
    unitPrice: 310,
  },
  {
    sku: 'WH-F03',
    product: '急件棧板標籤',
    zone: 'F03',
    stock: 3,
    reorderPoint: 8,
    reserved: 2,
    owner: 'Fang',
    channel: 'Enterprise',
    unitPrice: 180,
  },
];

export const orders = [
  {
    id: 'SO-20260705-018',
    customer: '辰海醫材',
    channel: 'B2B Portal',
    status: '待揀貨',
    priority: 'high',
    zone: 'A07',
    amount: 9520,
    eta: '14:30',
  },
  {
    id: 'SO-20260705-021',
    customer: '朗日餐飲集團',
    channel: 'LINE OA',
    status: '待出貨',
    priority: 'medium',
    zone: 'C08',
    amount: 4860,
    eta: '15:10',
  },
  {
    id: 'SO-20260705-025',
    customer: '禾森物流',
    channel: 'Enterprise',
    status: '已揀貨',
    priority: 'low',
    zone: 'D04',
    amount: 7440,
    eta: '16:20',
  },
  {
    id: 'SO-20260705-031',
    customer: '青石通路',
    channel: 'B2B Portal',
    status: '缺料等待',
    priority: 'high',
    zone: 'A01',
    amount: 12680,
    eta: '13:50',
  },
];

export const zones = [
  { id: 'A', label: '冷鏈區', utilization: 82, status: 'watch' },
  { id: 'B', label: '醫材區', utilization: 61, status: 'good' },
  { id: 'C', label: '耗材區', utilization: 88, status: 'risk' },
  { id: 'D', label: '溫控區', utilization: 54, status: 'good' },
];
